import test from 'node:test';
import assert from 'node:assert/strict';
import {prepareDraft,createDraft,verifyDraft} from '../lib/etsy-draft.mjs';
import {PRINT_PRODUCT} from '../lib/printshrimp-product.mjs';
const reference={shop_id:456,listing_id:789,state:'active',listing_type:'physical',price:{currency_code:'GBP'},taxonomy_id:123,shipping_profile_id:11,readiness_state_id:22,return_policy_id:33,who_made:'i_did',when_made:'made_to_order'};
const inventory={products:['A5','A4','A3'].map((size,i)=>({sku:'old-sku',property_values:[{property_id:513,property_name:'Size',value_ids:[i+1],values:[size]}],offerings:[{price:{amount:1000+i*500,divisor:100,currency_code:'GBP'},quantity:10,is_enabled:true,readiness_state_id:22}]}))};
const inputs={title:'Dinosaurs Across Time educational poster',description:'An unpublished physical dinosaur timeline print.',shopId:456};
test('draft plan uses real shop prices/settings and one SKU across three sizes',()=>{const p=prepareDraft(reference,inventory,inputs);assert.deepEqual(p.inventory.products.map(p=>p.offerings[0].price),[10,15,20]);assert.equal(p.body.shipping_profile_id,11);assert.equal(p.body.should_auto_renew,false);assert.equal(p.body.type,'physical');assert.equal(p.body.state,undefined);assert.deepEqual(p.inventory.sku_on_property,[]);assert.ok(p.inventory.products.every(p=>p.sku===PRINT_PRODUCT.sku));});
test('wrong shop, digital reference, unknown prices and ambiguous sizes fail closed',()=>{for(const r of [{...reference,shop_id:99},{...reference,listing_type:'download'},{...reference,readiness_state_id:null}])assert.throws(()=>prepareDraft(r,inventory,inputs));assert.throws(()=>prepareDraft(reference,{products:[...inventory.products,inventory.products[0]]},inputs));assert.throws(()=>prepareDraft(reference,{products:inventory.products.map(p=>({...p,offerings:[{...p.offerings[0],price:{amount:1000,divisor:100,currency_code:'USD'}}]}))},inputs));});
function fixture(fail=false){const records=new Map(),calls=[];let storedInventory;const client={session:async()=>({shop_id:456,shop_name:'SapiverPrints'}),api:async(path,o={})=>{calls.push([path,o]);if(path==='/listings/789')return reference;if(path==='/listings/789/inventory')return inventory;if(path.endsWith('/production-partners'))return {results:[{partner_name:'PrintShrimp',production_partner_id:55}]};if(path.startsWith('/shops/456/listings?'))return {count:0,results:[]};if(path==='/shops/456/listings'){if(fail)throw Error('timeout');return {listing_id:999,shop_id:456,state:'draft'};}if(path==='/listings/999/inventory'&&o.method==='PUT'){storedInventory=JSON.parse(o.body);return storedInventory;}if(path==='/listings/999/inventory')return storedInventory;if(path==='/listings/999')return {shop_id:456,state:'draft',listing_type:'physical'};return {};}};const store={setJSON:async(k,v,o)=>{if(o?.onlyIfNew&&records.has(k))return {modified:false};records.set(k,v);return {modified:true};}};return {client,store,records,calls};}
test('create draft verifies shop configuration, posts once, sets inventory and reads back without publication',async()=>{const f=fixture();const out=await createDraft({...f,...inputs,referenceListingId:789});assert.equal(out.listingId,999);assert.equal(f.records.get('draft/'+PRINT_PRODUCT.sku).phase,'verified');assert.equal(f.calls.filter(([,o])=>o.method==='POST').length,1);const body=new URLSearchParams(f.calls.find(([,o])=>o.method==='POST')[1].body);assert.equal(body.get('production_partner_ids'),'55');assert.equal(body.has('state'),false);await assert.rejects(createDraft({...f,...inputs,referenceListingId:789}),/reserved/);assert.equal(f.calls.filter(([,o])=>o.method==='POST').length,1);});
test('uncertain Etsy draft creation reserves product and blocks automatic duplicate',async()=>{const f=fixture(true);await assert.rejects(createDraft({...f,...inputs,referenceListingId:789}),/investigation/);await assert.rejects(createDraft({...f,...inputs,referenceListingId:789}),/reserved/);assert.equal(f.calls.filter(([,o])=>o.method==='POST').length,1);});
test('supplier verifier rejects active listing before reading inventory',async()=>{let calls=0;await assert.rejects(verifyDraft({listingId:999,client:{session:async()=>({shop_id:456}),api:async()=>{calls++;return {shop_id:456,state:'active',listing_type:'physical'};}}}));assert.equal(calls,1);});
test('existing shared SKU anywhere in shop blocks new draft before POST',async()=>{const f=fixture();const api=f.client.api;f.client.api=async(path,o)=>path.startsWith('/shops/456/listings?')?{count:1,results:[{shop_id:456,skus:[PRINT_PRODUCT.sku]}]}:api(path,o);await assert.rejects(createDraft({...f,...inputs,referenceListingId:789}),/already used/);assert.equal(f.calls.filter(([,o])=>o.method==='POST').length,0);assert.equal(f.records.size,0);});
