import test from 'node:test';
import assert from 'node:assert/strict';
import {createPosterOwnerHandler,createPosterRunner} from '../lib/poster-workflow.mjs';
import {seal} from '../lib/oauth.mjs';
const secret='test-encryption-key-for-poster-workflow';
const origin='https://poster.example.test';
const values={ETSY_PRINTS_KEYSTRING:'app',ETSY_PRINTS_SHARED_SECRET:'shared',CANVA_CLIENT_SECRET:secret,CANVA_SETUP_PASSWORD:'owner-password',CANVA_SITE_ORIGIN:origin,SHRIMP_APIKEY:'supplier-private'};
const env=n=>values[n];
function store(){const map=new Map();return {map,get:async k=>map.get(k),setJSON:async(k,v,o)=>{if(o?.onlyIfNew&&map.has(k))return {modified:false};map.set(k,v);return {modified:true};}};}
const auth=()=> '__Host-poster_owner='+seal({csrf:'owner-csrf',expiry:Date.now()+3600000},secret,'poster-owner');
const post=(fields,cookie=auth(),from=origin)=>new Request(origin+'/poster/workflow',{method:'POST',headers:{cookie,origin:from,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(fields)});
test('owner login uses password and cookie proof; missing/cross-site owner proof cannot queue work',async()=>{const jobs=store();const handler=createPosterOwnerHandler({env,jobs});let response=await handler(new Request(origin+'/poster/workflow'));assert.match(await response.text(),/type="password"/);assert.equal((await handler(post({csrf:'wrong',action:'draft',referenceListingId:'789'}))).status,403);assert.equal((await handler(post({csrf:'owner-csrf',action:'draft',referenceListingId:'789'},auth(),'https://evil.example.test'))).status,403);assert.equal(jobs.map.size,0);});
test('owner dispatch contains only sealed job ID and preserves queued command privately',async()=>{const jobs=store(),pending=[];let dispatch;const handler=createPosterOwnerHandler({env,jobs,request:async(url,o)=>{dispatch={url,...o};return new Response(null,{status:202});}});const response=await handler(post({csrf:'owner-csrf',action:'draft',referenceListingId:'789',title:'Dinosaurs Across Time',description:'Specific product description'}),{waitUntil:p=>pending.push(p)});await Promise.all(pending);assert.equal(response.status,303);assert.equal(dispatch.url,origin+'/poster/run');assert.doesNotMatch(dispatch.body,/supplier-private|Specific product|shared/);const job=[...jobs.map.values()][0];assert.equal(job.command.referenceListingId,789);assert.equal(job.phase,'queued');});
test('transfer requires explicit actual-master review before dispatch',async()=>{const jobs=store();const handler=createPosterOwnerHandler({env,jobs});assert.equal((await handler(post({csrf:'owner-csrf',action:'transfer',draftListingId:'999'}))).status,400);assert.equal(jobs.map.size,0);});
test('runner rejects forged and expired dispatch and claims valid job exactly once despite background retries',async()=>{const jobs=store(),etsyStore=store(),approvedStore=store(),jobId='a'.repeat(32);let calls=0;const runner=createPosterRunner({env,jobs,etsyStore,approvedStore,client:{session:async()=>{calls++;throw Error('private token failure');}}});await jobs.setJSON('jobs/'+jobId,{phase:'queued',command:{action:'draft',referenceListingId:789}});const req=body=>new Request(origin+'/poster/run',{method:'POST',body});await runner(req('forged'));await runner(req(seal({jobId,expiry:Date.now()-1},secret,'poster-runner')));assert.equal(calls,0);const ticket=seal({jobId,expiry:Date.now()+60000},secret,'poster-runner');await Promise.all([runner(req(ticket)),runner(req(ticket))]);assert.equal(calls,1);assert.equal(jobs.map.get('jobs/'+jobId).phase,'needs_investigation');await runner(req(ticket));assert.equal(calls,1);assert.doesNotMatch(JSON.stringify([...jobs.map.values()]),/private token failure/);});
import {inspectPNG} from '../lib/print-check.mjs';
import {PRINT_PRODUCT} from '../lib/printshrimp-product.mjs';
import {STATE_KEY} from '../lib/approved-export.mjs';
test('background pipeline creates verified draft first then transfers one stored master and revokes access',async()=>{
 const jobs=store(),etsyStore=store(),approvedStore=store();let mapped,posts=0,supplierGets=0,sourceUrl;
 const ref={shop_id:456,listing_id:789,state:'active',listing_type:'physical',price:{currency_code:'GBP'},taxonomy_id:123,shipping_profile_id:11,readiness_state_id:22,return_policy_id:33,who_made:'i_did',when_made:'made_to_order'};
 const refInventory={products:['A5','A4','A3'].map((s,i)=>({sku:'reference',property_values:[{property_id:513,value_ids:[i+1],values:[s]}],offerings:[{price:{amount:1000+i*500,divisor:100,currency_code:'GBP'},quantity:10,is_enabled:true,readiness_state_id:22}]}))};
 const client={session:async()=>({shop_id:456,shop_name:'SapiverPrints'}),api:async(path,o={})=>{if(path==='/listings/789')return ref;if(path==='/listings/789/inventory')return refInventory;if(path.startsWith('/shops/456/listings?'))return {count:0,results:[]};if(path.endsWith('/production-partners'))return {results:[{partner_name:'PrintShrimp',production_partner_id:55}]};if(path==='/shops/456/listings'){assert.equal(o.method,'POST');return {listing_id:999,shop_id:456,state:'draft'};}if(path==='/listings/999')return {shop_id:456,state:'draft',listing_type:'physical'};if(path==='/listings/999/inventory'){if(o.method==='PUT')mapped=JSON.parse(o.body);return mapped;}return {};}};
 const bytes=Buffer.alloc(33);Buffer.from([137,80,78,71,13,10,26,10]).copy(bytes);bytes.writeUInt32BE(13,8);bytes.write('IHDR',12);bytes.writeUInt32BE(3508,16);bytes.writeUInt32BE(4961,20);
 await approvedStore.setJSON(STATE_KEY,{phase:'ready_for_review',design_id:PRINT_PRODUCT.designId,approved_updated_at:PRINT_PRODUCT.approvedUpdatedAt,file_key:PRINT_PRODUCT.blobKey,image:inspectPNG(bytes),printshrimp:{meets_measured_upload_checks:true},readiness:{print_sizes:Object.fromEntries(['A5','A4','A3'].map(s=>[s,{passes_300ppi:true}]))}});await approvedStore.setJSON(PRINT_PRODUCT.blobKey,bytes);
 const runner=createPosterRunner({env,jobs,etsyStore,approvedStore,client,request:async(url,o)=>{if(o.method==='POST'){posts++;const p=JSON.parse(o.body);assert.equal(etsyStore.map.get('draft/'+PRINT_PRODUCT.sku).phase,'verified');assert.equal(new Set(p.variants.map(v=>v.image_url)).size,1);sourceUrl=p.variants[0].image_url;return Response.json({success:true},{status:201});}supplierGets++;if(supplierGets===1)return new Response(null,{status:404});return Response.json({success:true,product:{product_id:'supplier-product',sku:PRINT_PRODUCT.sku,variants:['A5','A4','A3'].map(size=>({size,image_url:'https://supplier.example.test/'+size+'.png'}))}});}});
 async function run(id,command){await jobs.setJSON('jobs/'+id,{phase:'queued',command});await runner(new Request(origin+'/poster/run',{method:'POST',body:seal({jobId:id,expiry:Date.now()+60000},secret,'poster-runner')}));return jobs.map.get('jobs/'+id);}
 const draft=await run('d'.repeat(32),{action:'draft',referenceListingId:789,title:'Dinosaurs Across Time educational poster',description:'Physical timeline poster for review.'});assert.equal(draft.phase,'complete');assert.equal(draft.result.listingId,999);
 const transfer=await run('t'.repeat(32),{action:'transfer',draftListingId:999,visualApproved:true});assert.equal(transfer.phase,'complete');assert.equal(posts,1);assert.equal(transfer.result.ordersEnabled,false);assert.equal(approvedStore.map.get('transfers/'+new URL(sourceUrl).searchParams.get('ticket')).revoked,true);
});
