import test from 'node:test';
import assert from 'node:assert/strict';
import sharp from 'sharp';
import {prepareUploadedPoster,publishUploadedPoster,assetKey,CHUNK_BYTES,hashBytes} from '../lib/uploaded-poster.mjs';
import {makePosterMockups} from '../lib/poster-mockups.mjs';
import {reference,inventory,shipping,processing,returns,carriers} from './fixtures/poster-template.mjs';
const id='a'.repeat(32),origin='https://poster.example.test';
function memory(){const map=new Map();return {map,get:async k=>map.get(k),set:async(k,v,o)=>{if(o?.onlyIfNew&&map.has(k))return {modified:false};map.set(k,v);return {modified:true};},setJSON:async(k,v,o)=>{if(o?.onlyIfNew&&map.has(k))return {modified:false};map.set(k,v);return {modified:true};}};}
async function fixture(){const uploads=memory(),etsyStore=memory(),calls=[];let mapped,listingState='draft',images=0;
const bytes=await sharp({create:{width:3508,height:4961,channels:3,background:'#cc8844'}}).png().toBuffer();await uploads.setJSON(assetKey(id),{phase:'preparing',filename:'SP-EL-006-DINOSAURS-ACROSS-TIME.png',referenceListingId:789,bytes:bytes.length,chunks:Math.ceil(bytes.length/CHUNK_BYTES)});for(let off=0,i=0;off<bytes.length;off+=CHUNK_BYTES,i++)await uploads.set('uploads/'+id+'/chunks/'+i,bytes.subarray(off,off+CHUNK_BYTES));
const client={session:async()=>({shop_id:456,shop_name:'SapiverPrints'}),api:async(path,o={})=>{calls.push([path,o]);if(path==='/listings/789')return reference;if(path==='/listings/789/inventory')return inventory;if(path.startsWith('/shipping-carriers?'))return carriers;if(path.includes('/shipping-profiles/'))return shipping;if(path.includes('/readiness-state-definitions/'))return processing;if(path.includes('/policies/return/'))return returns;if(path.endsWith('/production-partners'))return {results:[{partner_name:'PrintShrimp',location:'Romford, England',production_partner_id:55}]};if(path.startsWith('/shops/456/listings?'))return {count:0,results:[]};if(path==='/shops/456/listings')return {shop_id:456,state:'draft',listing_id:999};if(path==='/listings/999/inventory'){if(o.method==='PUT'){mapped=JSON.parse(o.body);return mapped;}return {products:mapped.products.map(p=>({...p,offerings:p.offerings.map(v=>({...v,price:{amount:Math.round(v.price*100),divisor:100,currency_code:'GBP'}}))}))};}if(path.endsWith('/images')&&o.method==='POST'){assert.ok(o.body instanceof FormData);images++;return {listing_image_id:images};}if(path==='/shops/456/listings/999'&&o.method==='PATCH'){assert.equal(images,3);assert.equal(o.body,'state=active');listingState='active';return {state:'active'};}if(path.startsWith('/listings/999')){const a=await uploads.get(assetKey(id));return {...a.plan.body,tags:a.plan.body.tags.split(','),is_personalizable:false,shop_id:456,state:listingState,listing_type:'physical',images:Array.from({length:images},(_,i)=>({listing_image_id:i+1}))};}throw Error('Unexpected endpoint');}};
const env=n=>({CANVA_SITE_ORIGIN:origin,SHRIMP_APIKEY:'private-key',POSTER_PUBLICATION_ENABLED:'true'}[n]);let gets=0,posts=0;
const request=async(url,o)=>{if(o.method==='POST'){posts++;assert.equal(listingState,'draft');const p=JSON.parse(o.body);assert.equal(new Set(p.variants.map(v=>v.image_url)).size,1);return Response.json({success:true},{status:201});}gets++;if(gets===1)return new Response(null,{status:404});return Response.json({success:true,product:{sku:'SP-EL-006-DINOSAURS-ACROSS-TIME',product_id:'supplier-product',variants:['A5','A4','A3'].map(size=>({size,image_url:'https://supplier.example.test/'+size+'.png'}))}});};
return {id,bytes,uploads,etsyStore,client,env,request,calls,posts:()=>posts};}
test('real PNG is decoded into three complete mockups; stored master bytes are unchanged',async()=>{const f=await fixture();await prepareUploadedPoster(f);const a=await f.uploads.get(assetKey(id));assert.equal(a.phase,'ready_for_approval');assert.equal(a.plan.inventory.products.length,12);assert.equal(hashBytes(await f.uploads.get(a.masterKey)),hashBytes(f.bytes));for(let i=0;i<3;i++){const m=await sharp(await f.uploads.get('uploads/'+id+'/mockups/'+i+'.jpg')).metadata();assert.equal(m.format,'jpeg');assert.equal(m.width,1200);assert.equal(m.height,1400);}});
test('approved exact file produces draft, twelve options, three images, one supplier POST, then publication',async()=>{const f=await fixture();await prepareUploadedPoster({...f,mockups:async()=>[Buffer.from('one'),Buffer.from('two'),Buffer.from('three')]});const a=await f.uploads.get(assetKey(id));await f.uploads.setJSON(assetKey(id),{...a,phase:'publishing'});const result=await publishUploadedPoster({...f,approvalHash:a.approvalHash});assert.equal(result.phase,'published');assert.equal(f.posts(),1);assert.equal(f.calls.filter(([,o])=>o.method==='PATCH').length,1);assert.ok([...f.uploads.map.entries()].some(([k,v])=>k.startsWith('transfers/')&&v.revoked));assert.equal(result.ordersEnabled,false);});
test('publication flag, wrong approval and mutated preview block all merchant writes',async()=>{const f=await fixture();await prepareUploadedPoster({...f,mockups:async()=>[1,2,3]});const a=await f.uploads.get(assetKey(id));await f.uploads.setJSON(assetKey(id),{...a,phase:'publishing'});const before=f.calls.length;await assert.rejects(publishUploadedPoster({...f,approvalHash:a.approvalHash,env:()=>undefined}),/not enabled/);await assert.rejects(publishUploadedPoster({...f,approvalHash:'wrong'}),/Approval/);a.plan.body.title='Changed after approval';await f.uploads.setJSON(assetKey(id),{...a,phase:'publishing'});await assert.rejects(publishUploadedPoster({...f,approvalHash:a.approvalHash}),/changed/);assert.equal(f.calls.length,before);assert.equal(f.posts(),0);});
test('supplier uncertainty prevents Etsy activation and revokes master access',async()=>{const f=await fixture();await prepareUploadedPoster({...f,mockups:async()=>[1,2,3]});const a=await f.uploads.get(assetKey(id));await f.uploads.setJSON(assetKey(id),{...a,phase:'publishing'});let gets=0;await assert.rejects(publishUploadedPoster({...f,approvalHash:a.approvalHash,request:async(url,o)=>{if(o.method==='POST')throw Error('private-key');gets++;return new Response(null,{status:404});}}));assert.equal(f.calls.filter(([,o])=>o.method==='PATCH').length,0);assert.ok([...f.uploads.map.values()].some(v=>v.revoked));});
