import yauzl from 'yauzl';
import yazl from 'yazl';
import {SaxesParser} from 'saxes';
import sharp from 'sharp';
import {crc32} from 'node:zlib';
import {PDFDocument,PDFDict,PDFArray,PDFName} from 'pdf-lib';
import {digest} from './product-metadata.mjs';
export const ZIP_MAX_BYTES=100_000_000,ETSY_FILE_MAX=20_000_000,ETSY_FILE_COUNT=5;
const ENTRY_MAX=50_000_000,TOTAL_MAX=200_000_000,COUNT_MAX=100,PIXELS_MAX=100_000_000;
const ALLOWED=new Set(['png','jpg','jpeg','pdf','svg','txt','md','json']);
const utf8=b=>new TextDecoder('utf-8',{fatal:true}).decode(b);
function svgSafe(bytes){const text=utf8(bytes);if(text.length>5_000_000||/<!DOCTYPE|<!ENTITY/i.test(text))throw Error('SVG entities are not allowed');let root=false;const parser=new SaxesParser({xmlns:true});parser.on('opentag',tag=>{if(!root){if(tag.local!=='svg'||tag.uri!=='http://www.w3.org/2000/svg')throw Error('Not an SVG');root=true;}if(['script','foreignObject','iframe','object','embed','animate','set','animateTransform'].includes(tag.local))throw Error('Active SVG content is not allowed');for(const a of Object.values(tag.attributes)){if(/^on/i.test(a.local)||((a.local==='href'||a.local==='src')&&!a.value.startsWith('#'))||/url\(\s*["']?(?!#)/i.test(a.value)||/@import/i.test(a.value))throw Error('External SVG content is not allowed');}});parser.on('text',t=>{if(/@import|url\(\s*["']?(?!#)/i.test(t))throw Error('External SVG style is not allowed');});parser.on('processinginstruction',()=>{throw Error('SVG processing instructions are not allowed');});parser.write(text).close();if(!root)throw Error('Invalid SVG');}
export async function inspectDigitalFile(name,data){const ext=name.split('.').pop().toLowerCase();if(!ALLOWED.has(ext))throw Error('Unsupported customer file: '+name);const info={name,format:ext,bytes:data.length,sha256:digest(data)};
 if(['png','jpg','jpeg'].includes(ext)){const image=sharp(data,{limitInputPixels:PIXELS_MAX,failOn:'warning'}),m=await image.metadata();if(m.format!==(ext==='png'?'png':'jpeg')||!m.width||!m.height||(m.pages||1)!==1)throw Error('Image content does not match its filename: '+name);await image.resize(1,1).raw().toBuffer();Object.assign(info,{width:m.width,height:m.height});}
 else if(ext==='svg'){svgSafe(data);await sharp(data,{limitInputPixels:PIXELS_MAX,failOn:'warning'}).resize(1,1).toBuffer();}
 else if(ext==='pdf'){if(data.length<10||!data.subarray(0,8).toString().startsWith('%PDF-')||!data.subarray(-2048).toString().includes('%%EOF')||/\/(JavaScript|JS|Launch|EmbeddedFile|RichMedia|OpenAction)\b/.test(data.toString('latin1')))throw Error('Invalid or active PDF: '+name);const pdf=await PDFDocument.load(data,{ignoreEncryption:false,updateMetadata:false});if(!pdf.getPageCount()||pdf.getPageCount()>100)throw Error('Invalid PDF page count');const seen=new Set();function check(obj){if(seen.has(obj))return;seen.add(obj);if(obj instanceof PDFDict){for(const [key,value] of obj.entries()){if(['JavaScript','JS','Launch','EmbeddedFile','RichMedia','OpenAction','AA','XFA'].includes(key.decodeText()))throw Error('Active PDF objects are not allowed');check(value);}}else if(obj instanceof PDFName&&['JavaScript','Launch','RichMedia','EmbeddedFile'].includes(obj.decodeText()))throw Error('Active PDF objects are not allowed');else if(obj?.dict)check(obj.dict);else if(obj instanceof PDFArray)for(const value of obj.asArray())check(value);}for(const [,obj] of pdf.context.enumerateIndirectObjects())check(obj);info.pages=pdf.getPageCount();info.pagePoints=pdf.getPages().map(p=>({width:p.getWidth(),height:p.getHeight()}));}
 else {if(data.length>2_000_000)throw Error('Text/metadata file too large');const text=utf8(data);if(text.includes('\0'))throw Error('Invalid text');if(ext==='json')JSON.parse(text);}
 return info;
}
export async function inspectArchive(bytes){if(bytes.length<22||bytes.length>ZIP_MAX_BYTES||bytes.readUInt32LE(0)!==0x04034b50)throw Error('Use a valid ZIP no larger than 100 MB');
 const zip=await new Promise((resolve,reject)=>yauzl.fromBuffer(bytes,{lazyEntries:true,strictFileNames:true,validateEntrySizes:true},(e,z)=>e?reject(e):resolve(z)));
 if(zip.entryCount>COUNT_MAX)throw Error('ZIP contains too many entries');
 const files=[],seen=new Set(),ranges=[],centralOffset=zip.readEntryCursor;let total=0;
 await new Promise((resolve,reject)=>{let failed=false;const fail=e=>{if(!failed){failed=true;zip.close();reject(e);}};zip.on('error',fail);zip.on('end',resolve);zip.on('entry',async entry=>{try{
  const offset=entry.relativeOffsetOfLocalHeader;if(offset<0||offset+30>bytes.length||bytes.readUInt32LE(offset)!==0x04034b50)throw Error('Invalid ZIP local header');const localFlags=bytes.readUInt16LE(offset+6),method=bytes.readUInt16LE(offset+8),nameLength=bytes.readUInt16LE(offset+26),extraLength=bytes.readUInt16LE(offset+28),dataStart=offset+30+nameLength+extraLength,dataEnd=dataStart+entry.compressedSize;if(localFlags!==entry.generalPurposeBitFlag||method!==entry.compressionMethod||dataEnd>centralOffset||bytes.subarray(offset+30,offset+30+nameLength).toString('utf8')!==entry.fileName||ranges.some(r=>offset<r.end&&dataEnd>r.start))throw Error('Archive header mismatch or overlapping data');ranges.push({start:offset,end:dataEnd});
  const name=entry.fileName,parts=name.split('/');if(name.length>200||/[\\\x00-\x1f<>:]/.test(name)||name.startsWith('/')||parts.some((p,i)=>p==='..'||p==='.'||(!p&&i!==parts.length-1))||parts.some(p=>/[. ]$/.test(p)||/^(CON|PRN|AUX|NUL|COM\d|LPT\d)(\.|$)/i.test(p)))throw Error('Unsafe archive filename');
  const normalized=name.normalize('NFC').toLowerCase();if(seen.has(normalized))throw Error('Duplicate archive filename');seen.add(normalized);
  const mode=entry.externalFileAttributes>>>16,type=mode&0xf000;if(type&&type!==0x8000&&type!==0x4000)throw Error('Archive links and special files are not allowed');if(entry.generalPurposeBitFlag&1||![0,8].includes(entry.compressionMethod))throw Error('Encrypted or unsupported ZIP');
  if(name.endsWith('/')){if(entry.uncompressedSize)throw Error('Invalid directory');zip.readEntry();return;}
  if(entry.uncompressedSize<=0||entry.uncompressedSize>ENTRY_MAX||entry.uncompressedSize/Math.max(1,entry.compressedSize)>100||(total+=entry.uncompressedSize)>TOTAL_MAX)throw Error('Archive expansion exceeds safe limits');
  const stream=await new Promise((r,j)=>zip.openReadStream(entry,(e,s)=>e?j(e):r(s))),buffers=[];let actual=0;for await(const chunk of stream){actual+=chunk.length;if(actual>entry.uncompressedSize||actual>ENTRY_MAX)throw Error('Archive expansion mismatch');buffers.push(chunk);}const data=Buffer.concat(buffers);if(actual!==entry.uncompressedSize||crc32(data)!==entry.crc32)throw Error('Archive checksum mismatch');
  const info=await inspectDigitalFile(name,data);files.push({...info,data});if(!failed)zip.readEntry();
 }catch(e){fail(e);}});zip.readEntry();});
 if(!files.some(f=>['png','jpg','jpeg','pdf','svg'].includes(f.format)))throw Error('ZIP needs an actual artwork file');return {files,bytes:bytes.length,sha256:digest(bytes),uncompressedBytes:total};
}
export async function zipFiles(files){const zip=new yazl.ZipFile(),chunks=[];const complete=new Promise((resolve,reject)=>{zip.outputStream.on('data',c=>chunks.push(c));zip.outputStream.on('error',reject);zip.outputStream.on('end',()=>resolve(Buffer.concat(chunks)));});for(const f of files)zip.addBuffer(f.data,f.name,{compressionLevel:9,mtime:new Date('2020-01-01T00:00:00Z'),mode:0o100644});zip.end();return complete;}
export async function packageForEtsy(original,inspection,metadata,{maxBytes=ETSY_FILE_MAX,maxFiles=ETSY_FILE_COUNT}={}){
 // Owner-written licensing/instructions are distinct supplementary files; source ZIP stays untouched.
 const guide={name:'SAPIVER-DOWNLOAD-AND-LICENCE.txt',format:'txt',generated:true,data:Buffer.from(metadata.instructions+'\n\nLicence:\n'+metadata.licence+'\n')};Object.assign(guide,{bytes:guide.data.length,sha256:digest(guide.data)});
 if(inspection.files.some(f=>f.name.toLowerCase()===guide.name.toLowerCase()))throw Error('Reserved guide filename; rename the existing file');
 if(original.length<=maxBytes&&guide.data.length<=maxBytes&&maxFiles>=2)return {files:[{name:'product.zip',bytes:original.length,sha256:digest(original),data:original},{name:guide.name,bytes:guide.bytes,sha256:guide.sha256,data:guide.data}],contents:[...inspection.files,guide],split:false};
 const source=[...inspection.files,guide],groups=[];let group=[];
 // Exact compressed archive sizes, not estimates; each output is an independent ZIP.
 for(const f of source){const candidate=await zipFiles([...group,f]);if(candidate.length<=maxBytes){group.push(f);continue;}if(!group.length)throw Error('An individual file cannot fit Etsy’s 20 MB limit without changing it: '+f.name);groups.push(group);group=[f];if((await zipFiles(group)).length>maxBytes)throw Error('An individual file cannot fit Etsy’s 20 MB limit without changing it: '+f.name);}
 if(group.length)groups.push(group);if(groups.length>maxFiles)throw Error('Package needs more than Etsy’s five files; reduce the source package');
 const files=[];for(let i=0;i<groups.length;i++){const data=await zipFiles(groups[i]);files.push({name:'product-part-'+(i+1)+'.zip',bytes:data.length,sha256:digest(data),data});}return {files,contents:source,split:true};
}
export async function digitalPreviews(files){const candidates=files.filter(f=>['png','jpg','jpeg','svg'].includes(f.format)).sort((a,b)=>Number(/preview|repeat/i.test(b.name))-Number(/preview|repeat/i.test(a.name)));
 if(!candidates.length)throw Error('Include a PNG/JPG/SVG listing preview for a PDF-only package');
 const images=[];for(const f of candidates.slice(0,3)){const art=await sharp(f.data,{limitInputPixels:PIXELS_MAX,failOn:'warning'}).rotate().resize(1100,1100,{fit:'inside',withoutEnlargement:true}).flatten({background:'#f7f3ec'}).png().toBuffer(),m=await sharp(art).metadata();const label=Buffer.from('<svg width="1200" height="100"><rect width="1200" height="100" fill="#213333"/><text x="600" y="60" text-anchor="middle" font-family="sans-serif" font-size="28" fill="white">Digital download • No physical item</text></svg>');images.push(await sharp({create:{width:1200,height:1300,channels:3,background:'#f7f3ec'}}).composite([{input:art,left:Math.floor((1200-m.width)/2),top:Math.floor((1200-m.height)/2)},{input:label,left:0,top:1200}]).jpeg({quality:90}).toBuffer());}return images;
}
