import {inspectArchive,packageForEtsy,digitalPreviews,inspectDigitalFile,ETSY_FILE_MAX,ETSY_FILE_COUNT,ZIP_MAX_BYTES} from './digital-archive.mjs';
import {digitalListingText,selectTaxonomy,digest,PRODUCT_VERSION} from './product-metadata.mjs';
import {recordKey,recordRevision,validId,ensureSection} from './product-records.mjs';
const stateKey=id=>'uploads/'+id+'/state';
export async function readUploadChunks(uploads,asset,id){const buffers=[];for(let i=0;i<asset.chunks;i++){const b=await uploads.get('uploads/'+(asset.reuseChunkId||id)+'/chunks/'+i,{type:'arrayBuffer',consistency:'strong'});if(!b||b.byteLength!==Math.min(2_000_000,asset.bytes-i*2_000_000))throw Error('Missing or mismatched upload chunk');buffers.push(Buffer.from(b));}const bytes=Buffer.concat(buffers);if(bytes.length!==asset.bytes)throw Error('Upload length mismatch');return bytes;}
export function listingSnapshot(l,files){return {listing_id:l.listing_id,shop_id:l.shop_id,state:l.state,listing_type:l.listing_type,title:l.title,description:l.description,price:l.price,tags:l.tags,taxonomy_id:l.taxonomy_id,shop_section_id:l.shop_section_id,fileIds:files.results?.map(f=>({id:f.listing_file_id,name:f.filename,bytes:f.size_bytes})).sort((a,b)=>a.id-b.id)};}
export async function prepareDigitalProduct({id,uploads,client}){
 let asset=await uploads.get(stateKey(id),{type:'json',consistency:'strong'});if(!validId(id)||asset?.type!=='digital'||asset.phase!=='preparing')throw Error('Digital product not ready');
 const bytes=asset.reuseArchiveKey?Buffer.from(await uploads.get(asset.reuseArchiveKey,{type:'arrayBuffer',consistency:'strong'})):await readUploadChunks(uploads,asset,id);if(bytes.length>ZIP_MAX_BYTES)throw Error('ZIP exceeds upload limit');
 const earlyArchiveKey='uploads/'+id+'/original.zip';await uploads.set(earlyArchiveKey,bytes);asset={...asset,archiveKey:earlyArchiveKey,stage:'validating_upload'};await uploads.setJSON(stateKey(id),asset);const inspection=await inspectArchive(bytes),delivery=await packageForEtsy(bytes,inspection,asset.metadata),taxonomy=selectTaxonomy(asset.metadata,(await client.api('/seller-taxonomy/nodes')).results);
 const seller=await client.session();if(seller.shop_name&&seller.shop_name!=='SapiverPrints')throw Error('Wrong shop');
 let previous=null;if(asset.updateProductId){const record=await uploads.get(recordKey(asset.updateProductId),{type:'json',consistency:'strong'});if(record?.type!=='digital'||!Number.isSafeInteger(record.etsyListingId))throw Error('Existing digital product required');const listing=await client.api('/listings/'+record.etsyListingId),files=await client.api('/shops/'+seller.shop_id+'/listings/'+record.etsyListingId+'/files');if(listing.shop_id!==seller.shop_id||listing.listing_type!=='download'||!['active','inactive'].includes(listing.state))throw Error('Existing listing is not this shop’s digital product');previous=listingSnapshot(listing,files);}
 const previewInputs=[...inspection.files];for(let i=0;i<(asset.sourcePreviewCount??asset.previewCount??0);i++){const data=Buffer.from(await uploads.get(asset.reusePreviewKeys?.[i]||'uploads/'+id+'/preview-input/'+i+'.jpg',{type:'arrayBuffer',consistency:'strong'}));previewInputs.unshift({...await inspectDigitalFile('preview-'+i+'.jpg',data),data});}
 const images=await digitalPreviews(previewInputs),archiveKey='uploads/'+id+'/original.zip';await uploads.set(archiveKey,bytes);
 const parts=[];for(let i=0;i<delivery.files.length;i++){const f=delivery.files[i],key='uploads/'+id+'/delivery/'+i;await uploads.set(key,f.data);parts.push({key,name:f.name,bytes:f.bytes,sha256:f.sha256});}
 const previewHashes=[];for(let i=0;i<images.length;i++){await uploads.set('uploads/'+id+'/mockups/'+i+'.jpg',images[i]);previewHashes.push(digest(images[i]));}
 const contents=delivery.contents.map(({data,...info})=>info),text=digitalListingText(asset.metadata,contents);
 const plan={version:PRODUCT_VERSION,type:'digital',metadata:asset.metadata,taxonomy,sectionTitle:asset.metadata.sectionTitle,sourceHash:inspection.sha256,contents,parts,previewHashes,previous,body:{quantity:999,title:text.title,description:text.description,price:asset.metadata.price,who_made:'i_did',when_made:'2020_2026',taxonomy_id:taxonomy.id,type:'download',is_supply:false,should_auto_renew:false,tags:text.tags.join(',')}};
 const approvalHash=digest(plan);await uploads.setJSON(stateKey(id),{...asset,phase:'ready_for_approval',archiveKey,contents,plan,approvalHash,previewCount:images.length,sourceHash:inspection.sha256,split:delivery.split});await recordRevision(uploads,id);
 for(let i=0;i<asset.chunks;i++)try{await uploads.delete('uploads/'+(asset.reuseChunkId||id)+'/chunks/'+i);}catch{}
}
function verifyListing(l,plan,shopId,state,sectionId){if(l.shop_id!==shopId||l.state!==state||l.listing_type!=='download'||l.has_variations===true||l.shipping_profile_id||l.readiness_state_id||l.is_personalizable===true)throw Error('Digital listing type or settings mismatch');for(const k of ['title','description','taxonomy_id','who_made','when_made'])if(l[k]!==plan.body[k])throw Error('Digital listing read-back mismatch');if(l.price?.currency_code!=='GBP'||l.price.amount/l.price.divisor!==plan.body.price||l.shop_section_id!==sectionId||!Array.isArray(l.tags)||l.tags.slice().sort().join('|')!==plan.body.tags.split(',').sort().join('|'))throw Error('Digital price, tags or section mismatch');}
function verifyFiles(result,parts,listingId){if(result.count!==parts.length||result.results?.length!==parts.length||parts.length>ETSY_FILE_COUNT)throw Error('Digital file count mismatch');for(const p of parts){const matches=result.results.filter(f=>f.filename===p.name&&f.size_bytes===p.bytes&&f.listing_id===listingId&&Number.isSafeInteger(f.listing_file_id));if(matches.length!==1)throw Error('Customer file read-back mismatch');}}
export async function publishDigitalProduct({id,approvalHash,uploads,etsyStore,client,env}){
 if(env('POSTER_PUBLICATION_ENABLED')!=='true')throw Error('Publication is disabled');let asset=await uploads.get(stateKey(id),{type:'json',consistency:'strong'});const approval=await uploads.get('claims/'+id+'/publish',{type:'json',consistency:'strong'});
 if(!validId(id)||asset?.type!=='digital'||asset.phase!=='publishing'||approval?.approvalHash!==approvalHash||asset.approvalHash!==approvalHash||asset.plan?.version!==PRODUCT_VERSION||digest(asset.plan)!==approvalHash)throw Error('Exact owner Deploy approval required');
 const product=await uploads.get(recordKey(asset.productId||id),{type:'json',consistency:'strong'});if(product?.pendingRevision!==id)throw Error('Product review superseded');const plan=asset.plan,seller=await client.session();if(digest(Buffer.from(await uploads.get(asset.archiveKey,{type:'arrayBuffer',consistency:'strong'})))!==plan.sourceHash)throw Error('Original ZIP changed after approval');
 const parts=[];for(const p of plan.parts){const bytes=Buffer.from(await uploads.get(p.key,{type:'arrayBuffer',consistency:'strong'}));if(bytes.length!==p.bytes||bytes.length>ETSY_FILE_MAX||digest(bytes)!==p.sha256)throw Error('Customer package changed');parts.push({...p,data:bytes});}if(!parts.length||parts.length>ETSY_FILE_COUNT)throw Error('Invalid digital delivery');
 const images=[];for(let i=0;i<plan.previewHashes.length;i++){const bytes=Buffer.from(await uploads.get('uploads/'+id+'/mockups/'+i+'.jpg',{type:'arrayBuffer',consistency:'strong'}));if(digest(bytes)!==plan.previewHashes[i])throw Error('Preview changed after approval');images.push(bytes);}
 const available=selectTaxonomy({...plan.metadata,taxonomyId:plan.taxonomy.id},(await client.api('/seller-taxonomy/nodes')).results);if(available.path!==plan.taxonomy.path)throw Error('Marketplace category changed');
 const productId=asset.productId||id,reserved=await etsyStore.setJSON('products/'+productId+'/revision/'+id,{phase:'reserved',approvalHash},{onlyIfNew:true});if(reserved?.modified!==true)throw Error('This revision already has an Etsy reservation; inspect status');
 const save=async patch=>{asset={...asset,...patch};await uploads.setJSON(stateKey(id),asset);await recordRevision(uploads,id);};
 let listingId;const sectionId=await ensureSection({client,shopId:seller.shop_id,title:plan.sectionTitle,store:etsyStore});
 if(plan.previous){const record=await uploads.get(recordKey(productId),{type:'json',consistency:'strong'});if(record?.etsyListingId!==plan.previous.listing_id)throw Error('Product listing mapping changed');listingId=record.etsyListingId;const current=await client.api('/listings/'+listingId),files=await client.api('/shops/'+seller.shop_id+'/listings/'+listingId+'/files');if(digest(listingSnapshot(current,files))!==digest(plan.previous))throw Error('Existing listing changed since review');await save({listingId,etsyUrl:record.etsyUrl,stage:'deactivating_for_update'});
  await client.api('/shops/'+seller.shop_id+'/listings/'+listingId,{method:'PATCH',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'state=inactive'});const inactive=await client.api('/listings/'+listingId);if(inactive.state!=='inactive'||inactive.shop_id!==seller.shop_id)throw Error('Could not safely deactivate update');
  for(const f of files.results)await client.api('/shops/'+seller.shop_id+'/listings/'+listingId+'/files/'+f.listing_file_id,{method:'DELETE'});
  await client.api('/shops/'+seller.shop_id+'/listings/'+listingId,{method:'PATCH',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(Object.entries({...plan.body,shop_section_id:sectionId}).map(([k,v])=>[k,String(v)])).toString()});
 }else{
  const identityLock=await etsyStore.setJSON('digital-identity/'+digest(plan.metadata.sku),{productId,revisionId:id},{onlyIfNew:true});if(identityLock?.modified!==true)throw Error('This digital SKU is already reserved; update the existing product');
  await save({stage:'creating_digital_draft'});const unique=await etsyStore.setJSON('product-create/'+productId,{phase:'creating',revisionId:id},{onlyIfNew:true});if(unique?.modified!==true)throw Error('Product creation already reserved; no duplicate listing');
  const l=await client.api('/shops/'+seller.shop_id+'/listings',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(Object.entries({...plan.body,shop_section_id:sectionId}).map(([k,v])=>[k,String(v)])).toString()});if(l.shop_id!==seller.shop_id||l.state!=='draft'||!Number.isSafeInteger(l.listing_id))throw Error('Draft response mismatch');listingId=l.listing_id;await save({listingId,stage:'digital_draft'});
 }
 const base='/shops/'+seller.shop_id+'/listings/'+listingId;const ids=[];
 for(let i=0;i<parts.length;i++){const p=parts[i],form=new FormData();form.set('file',new Blob([p.data],{type:p.name.endsWith('.zip')?'application/zip':'text/plain'}),p.name);form.set('name',p.name);form.set('rank',String(i+1));const result=await client.api(base+'/files',{method:'POST',body:form});if(!Number.isSafeInteger(result.listing_file_id)||result.listing_id!==listingId||result.filename!==p.name||result.size_bytes!==p.bytes)throw Error('Digital file upload response mismatch');ids.push(result.listing_file_id);await save({stage:'attaching_downloads',etsyFileIds:ids});}
 const imageIds=[];for(let i=0;i<images.length;i++){const form=new FormData();form.set('image',new Blob([images[i]],{type:'image/jpeg'}),'preview-'+(i+1)+'.jpg');form.set('rank',String(i+1));const r=await client.api(base+'/images',{method:'POST',body:form});if(!Number.isSafeInteger(r.listing_image_id)||r.listing_id!==listingId)throw Error('Preview upload response mismatch');imageIds.push(r.listing_image_id);}
 // Explicit image IDs replace the visible set on updates without duplicating old previews.
 await client.api(base,{method:'PATCH',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({type:'download',image_ids:imageIds.join(','),shop_section_id:String(sectionId)}).toString()});
 verifyFiles(await client.api(base+'/files'),parts,listingId);const checked=await client.api('/listings/'+listingId+'?includes=Images');verifyListing(checked,plan,seller.shop_id,plan.previous?'inactive':'draft',sectionId);if(checked.images?.length!==imageIds.length||imageIds.some(n=>!checked.images.some(i=>i.listing_image_id===n)))throw Error('Preview read-back mismatch');
 await save({stage:'publishing_etsy'});await client.api(base,{method:'PATCH',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'state=active'});const active=await client.api('/listings/'+listingId);verifyListing(active,plan,seller.shop_id,'active',sectionId);verifyFiles(await client.api(base+'/files'),parts,listingId);
 if(typeof active.url!=='string'||!/^https:\/\/(www\.)?etsy\.com\//.test(active.url))throw Error('Etsy listing URL unavailable');await save({phase:'published',stage:'complete',etsyUrl:active.url,publishedAt:Date.now()});return {listingId,url:active.url};
}
