// Shared presentation only. Sessions, form fields and publication gates live in their handlers.
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const ownerStyles=`
:root{color-scheme:light;--ink:#203d36;--muted:#61726b;--paper:#f6f4ee;--line:#dce3db;--gold:#d3ad68;--white:#fff; font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-size:16px;line-height:1.65}a{color:var(--ink);text-underline-offset:4px}a:hover{text-decoration-thickness:2px}button,input,select,textarea{font:inherit}button,a,input,select,textarea,summary{-webkit-tap-highlight-color:transparent}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible,summary:focus-visible{outline:3px solid #ba842d;outline-offset:4px}[hidden]{display:none!important}
.site-header{background:var(--ink);color:var(--white)}.header-inner{max-width:1120px;margin:auto;min-height:90px;padding:20px 32px;display:flex;align-items:center;justify-content:space-between;gap:24px}.brand{display:flex;align-items:center;gap:14px;color:white;text-decoration:none}.brand-mark{display:grid;place-items:center;width:46px;height:46px;border:1px solid #ffffff50;border-radius:14px;color:#ead2a4;font-family:Georgia,serif;font-size:22px}.brand-name{display:block;font-size:20px;font-weight:700;letter-spacing:-.4px}.brand-caption{display:block;font-size:11px;letter-spacing:2px;text-transform:uppercase;color:#c8d6cd}.site-nav{display:flex;gap:8px;flex-wrap:wrap}.site-nav a{color:white;text-decoration:none;padding:9px 16px;border-radius:9px;font-size:14px}.site-nav a:hover,.site-nav a[aria-current=page]{background:#ffffff17}.site-nav .nav-new{background:#e4c48e;color:#203d36;font-weight:700}
.workspace{max-width:1060px;margin:0 auto;padding:42px 32px 64px}.eyebrow{margin:0 0 10px;color:#62766b;font-size:11px;font-weight:750;letter-spacing:2px;text-transform:uppercase}.page-intro{margin-bottom:30px}h1{font-family:Georgia,"Times New Roman",serif;font-weight:400;font-size:clamp(32px,5vw,46px);line-height:1.15;letter-spacing:-1.2px;margin:0 0 14px}h2{font-size:26px;line-height:1.3;letter-spacing:-.6px;margin:0 0 14px}h3{font-size:20px;line-height:1.4;margin:24px 0 10px}p{margin:0 0 18px}p,li,pre{overflow-wrap:anywhere}.intro-copy{color:var(--muted);max-width:650px;margin:0}.steps{display:flex;gap:24px;flex-wrap:wrap;padding:16px 0 24px;border-bottom:1px solid var(--line);margin:0 0 30px;list-style:none;font-size:13px;color:var(--muted)}.steps li{display:flex;align-items:center;gap:9px}.step-number{display:grid;place-items:center;width:26px;height:26px;background:#e4eade;border-radius:50%;color:var(--ink);font-weight:700}
.content>form,fieldset,article,.login-card{background:var(--white);border:1px solid var(--line);border-radius:18px;padding:28px;margin:22px 0;box-shadow:0 3px 12px #203d3604}.content>form{margin-top:20px}fieldset{box-shadow:none;margin:24px 0;padding:24px}legend{padding:0 8px;font-size:15px;font-weight:750}.content label{display:block;font-size:14px;font-weight:650;margin:0 0 20px}.content input:not([type=checkbox]):not([type=hidden]),select,textarea{display:block;width:100%;min-height:48px;border:1px solid #cbd6cd;border-radius:9px;padding:11px 13px;margin-top:7px;background:#fff;color:var(--ink)}textarea{min-height:125px;resize:vertical;line-height:1.55}.content input[type=checkbox]{accent-color:var(--ink);width:18px;height:18px;vertical-align:middle;margin-right:8px}.content input[type=file]{padding:15px;background:#f8faf6!important;border:1px dashed #a9bdae!important;min-height:92px}.content input[type=file]::file-selector-button{border:0;border-radius:7px;padding:10px 14px;background:#e4ebdf;color:var(--ink);font-weight:650;margin-right:14px;cursor:pointer}button{min-height:46px;max-width:100%;border:0;border-radius:9px;padding:11px 20px;background:var(--ink);color:white;font-size:14px;font-weight:700;cursor:pointer;white-space:normal}button:hover:not(:disabled){background:#31574b}button[type=button]{background:#edf1e9;color:var(--ink);font-weight:600}button:disabled{background:#e4e8e1;color:#718076;cursor:not-allowed}.content form>button{margin:6px 0 0}.content form>p{font-size:14px;color:var(--muted)}.content img{display:inline-block;max-width:100%;height:auto;border-radius:12px;border:1px solid var(--line);margin:8px 12px 12px 0;vertical-align:top}.content pre{font-family:inherit;font-size:14px;line-height:1.7;background:#eef2e9;border-radius:12px;padding:22px;white-space:pre-wrap}.content table{width:100%;border-collapse:collapse;margin:22px 0;font-size:14px}.content th,.content td{padding:13px 10px;border-bottom:1px solid var(--line);text-align:left}.content th{background:#edf1e8;font-weight:700}.content details{border:1px solid var(--line);border-radius:12px;padding:18px;margin:24px 0}.content summary{cursor:pointer;font-weight:650}.content [role=alert]{background:#fff0e9;color:#844024;border:1px solid #edcdbc;border-radius:10px;padding:16px}#upload-status:not(:empty),#clipboard-status:not(:empty){background:#edf1e7;border-radius:10px;padding:16px;font-size:14px}.login .workspace{max-width:760px}.login .content>form{max-width:580px;margin:0 auto;padding:32px}.login .page-intro{text-align:center}.login .intro-copy{margin:0 auto}.site-footer{border-top:1px solid var(--line);padding:24px 32px;text-align:center;color:var(--muted);font-size:12px}.content>article h3{margin-top:0}.content>form:has(select[name=status]){display:grid;grid-template-columns:1fr 1fr 1fr auto;gap:16px;align-items:end}.content>form:has(select[name=status]) label{margin:0}.content>form:has(select[name=status]) button{margin-bottom:0}
@media(min-width:760px){fieldset{display:grid;grid-template-columns:1fr 1fr;gap:0 22px}fieldset>div,fieldset>p,fieldset>label:has(textarea),fieldset>label:has(input[name=tags]),fieldset>label:has(select[name=taxonomyId]){grid-column:1/-1}}
@media(max-width:620px){.header-inner{padding:18px 20px;align-items:flex-start;gap:16px;flex-direction:column}.site-nav{width:100%;gap:4px}.site-nav a{padding:8px 12px}.workspace{padding:30px 20px 44px}.steps{gap:14px;font-size:12px}.content>form,fieldset,article,.login .content>form{padding:20px;border-radius:14px}fieldset{padding:16px}.content>form:has(select[name=status]){grid-template-columns:1fr}.content input[type=file]::file-selector-button{display:block;margin:0 0 9px}.content img{width:100%;margin-right:0}.content table{font-size:12px}.content td,.content th{padding:10px 5px}button{min-height:48px}.login .page-intro{text-align:left}.brand-name{font-size:19px}}
@media(prefers-reduced-motion:no-preference){button,a,input,select,textarea{transition:background-color .15s,border-color .15s}}
`;
export function renderOwnerPage({title='Product studio',body,csrf='',login=false,active='upload'}){
const nav=login?'':`<nav class="site-nav" aria-label="Product studio"><a href="/poster/products" ${active==='products'?'aria-current="page"':''}>Products</a><a class="nav-new" href="/poster/upload" ${active==='upload'?'aria-current="page"':''}>New product</a></nav>`;
const intro=login?'<p class="eyebrow">Your private product studio</p><h1>Welcome back.</h1><p class="intro-copy">Manage your artwork, prepare your listings and review every product before it goes on sale.</p>':`<p class="eyebrow">Sapiver Prints · Product studio</p><h1>${escape(title)}</h1><p class="intro-copy">A single home for your printed artwork and digital downloads.</p>`;
const steps=!login&&active==='upload'?'<ol class="steps" aria-label="Product workflow"><li><span class="step-number">1</span> Upload your artwork</li><li><span class="step-number">2</span> Review your product</li><li><span class="step-number">3</span> Approve for Etsy</li></ol>':'';
return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="poster-csrf" content="${escape(csrf)}"><title>${escape(title)} · Sapiver Prints</title><style>${ownerStyles}</style></head><body class="${login?'login':'studio'}"><header class="site-header"><div class="header-inner"><a class="brand" href="/poster/upload"><span class="brand-mark" aria-hidden="true">SP</span><span><span class="brand-name">Sapiver Prints</span><span class="brand-caption">Create. Review. Publish.</span></span></a>${nav}</div></header><main class="workspace"><div class="page-intro">${intro}</div>${steps}<div class="content">${body}</div></main><footer class="site-footer">Sapiver Prints · Your original files stay private until you approve a product.</footer></body></html>`;
}
