import {randomBytes} from 'node:crypto';
import {digest} from './product-metadata.mjs';
export const validId=id=>typeof id==='string'&&/^[A-Za-z0-9_-]{32}$/.test(id);
export const recordKey=id=>'products/'+id+'/record';
export async function recordRevision(uploads,id){const asset=await uploads.get('uploads/'+id+'/state',{type:'json',consistency:'strong'});if(!asset)return;const productId=asset.productId||id,old=await uploads.get(recordKey(productId),{type:'json',consistency:'strong'});
 const patch={productId,type:asset.type||'physical',metadata:asset.phase!=='published'&&old?.currentRevision?old.metadata:asset.metadata||old?.metadata||{name:asset.plan?.identity?.name||asset.filename,kind:'educational',subject:asset.plan?.identity?.name},createdAt:old?.createdAt||asset.createdAt,currentRevision:asset.phase==='published'?id:old?.currentRevision||null,pendingRevision:asset.phase==='published'?null:id,pendingPhase:asset.phase==='published'?null:asset.phase,phase:asset.phase==='published'?'published':asset.phase==='needs_investigation'?'needs_investigation':asset.updateProductId&&asset.stage?'updating':old?.phase==='published'?'published':asset.phase,etsyListingId:asset.listingId||old?.etsyListingId||null,etsyUrl:asset.etsyUrl||old?.etsyUrl||null,supplierProductId:asset.supplierProductId||old?.supplierProductId||null,files:asset.phase!=='published'&&old?.currentRevision?old.files:asset.contents||old?.files||[{name:asset.filename,bytes:asset.bytes}],previewId:asset.phase==='published'||!old?.previewId?id:old.previewId,lastError:asset.failureCode||null,updatedAt:Date.now()};
 await uploads.setJSON(recordKey(productId),{...old,...patch});await uploads.setJSON('products/'+productId+'/revisions/'+id,{id,phase:asset.phase,at:Date.now(),listingId:patch.etsyListingId});return patch;
}
export async function listProducts(uploads){const products=[];for await(const page of uploads.list({prefix:'products/',paginate:true})){for(const b of page.blobs){if(/^products\/[A-Za-z0-9_-]{32}\/record$/.test(b.key)){const r=await uploads.get(b.key,{type:'json',consistency:'strong'});if(r)products.push(r);}}}return products.sort((a,b)=>b.updatedAt-a.updatedAt);}
export async function ensureSection({client,shopId,title,store}){if(!title||title.length>24)throw Error('Invalid shop section');const sections=await client.api('/shops/'+shopId+'/sections');if(!Array.isArray(sections.results))throw Error('Shop sections unavailable');const match=sections.results.filter(s=>s.title.trim().toLowerCase()===title.trim().toLowerCase());if(match.length===1)return match[0].shop_section_id;if(match.length>1)throw Error('Duplicate existing shop sections need attention');if(sections.results.length>=20)throw Error('Etsy shop already has twenty sections');
 const lock=await store.setJSON('sections/'+digest(title.toLowerCase()),{phase:'creating',title},{onlyIfNew:true});if(lock?.modified!==true)throw Error('Section creation already reserved; inspect before retry');
 const created=await client.api('/shops/'+shopId+'/sections',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({title}).toString()});if(!Number.isSafeInteger(created.shop_section_id)||created.shop_section_id<=0||created.title!==title)throw Error('Section response mismatch');
 const check=await client.api('/shops/'+shopId+'/sections');if(check.results?.filter(s=>s.title.trim().toLowerCase()===title.toLowerCase()).length!==1||!check.results.some(s=>s.shop_section_id===created.shop_section_id))throw Error('Section read-back mismatch');await store.setJSON('sections/'+digest(title.toLowerCase()),{phase:'complete',title,id:created.shop_section_id});return created.shop_section_id;
}
export function newId(){return randomBytes(24).toString('base64url');}
